name: CIPR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - 'master'
      - '!l10n_*' # don't run from a crowdin PR

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.18.1
          check-latest: true

      - name: Install dependencies
        run: |
          npm install -g npm@8.3.1
          npm ci

      - name: Build
        run: |
          git lfs pull
          npm run validate-files
          npm run build:dist

      - name: Build Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: npm run build:linux -- --publish=never

      - name: Build Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm run build:win -- --publish=never

      - name: Build Mac
        if: ${{ matrix.os == 'macOS-latest' }}
        run: npm run build:mac -- --publish=never
